{% set name = "ypywidgets-textual" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ypywidgets_textual-{{ version }}.tar.gz
  sha256: b9b97d7fabe727f3ed08ab80fbd2788c729e1165d74789fcecb550c35557442c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - ypywidgets >=0.7.0,<0.8.0
    - textual >=0.41.0
    - textual-plotext
    - pyte

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - ypywidgets_textual

about:
  home: https://github.com/davidbrochart/ypywidgets-textual
  summary: Textual widgets for ypywidgets
  dev_url: https://github.com/davidbrochart/ypywidgets-textual
  license_file: LICENSE
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
