{% set name = "ypywidgets-textual" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ypywidgets_textual-{{ version }}.tar.gz
  sha256: afe398192b6cd260a5c841c91af19e3a381369730eef506518c1a56df742884f

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - ypywidgets >=0.9.0,<0.10.0
    - textual >=0.41.0
    - textual-plotext
    - pyte

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - ypywidgets_textual

about:
  home: https://github.com/davidbrochart/ypywidgets-textual
  summary: Textual widgets for ypywidgets
  dev_url: https://github.com/davidbrochart/ypywidgets-textual
  license_file: LICENSE
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
